# Generated by Django 2.2.16 on 2023-01-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(
                auto_now_add=True, default='2012-09-04 06:00:00.000000-08:00'
            ),
            preserve_default=False,
        ),
    ]
